# on every push to any branch builds the project fully
name: ci
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.data/**'
jobs:
  ci:
    name: CI
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Markdown lint
        uses: actionshub/markdownlint@v3.1.4

      - name: Black
        uses: psf/black@stable
